title: Nicholas Gray
github: ngg1995
location: Liverpool, UK

description: >-
  Postdoctoral researcher specialising in AI risk, uncertainty quantification,
  and responsible AI deployment in clinical settings.

baseurl: ""
url: "https://nickgray.info"

markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
